language: node_js
node_js:
  - "9"

branches:
  only:
    - master
    - develop

before_script:
- npm install

script:
- npm run build

after_success:
- npm pack

deploy: 
  provider: npm 
  email: rromero@digitaltpm.com 
  api_key: NPM_API_KEY
  on: 
    branch: master
